{
  "formatVersion": "1.1",
  "component": {
    "group": "transformer.plugin",
    "module": "transformerPlugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "transformerPlugin-0.0.1.jar",
          "url": "transformerPlugin-0.0.1.jar",
          "size": 15277,
          "sha512": "4a7b62a70ecafdee52b5990cf9fd48b94e961d750d51fdac2aee72919bda8cfd627b3cf8b2e3011e63fba69328b5e1a01188a03b695c1bc21a0b48f7939b743e",
          "sha256": "ea7c90b186660a1cc17641f4a1c986d6f1a0ffcc8cf682effa94bbfdeacd9341",
          "sha1": "9a6a8248b6ea2d5df36868ff8881278bc1c2397c",
          "md5": "c4d0af565856c7b0288a9957b7069ea0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "transformerPlugin-0.0.1.jar",
          "url": "transformerPlugin-0.0.1.jar",
          "size": 15277,
          "sha512": "4a7b62a70ecafdee52b5990cf9fd48b94e961d750d51fdac2aee72919bda8cfd627b3cf8b2e3011e63fba69328b5e1a01188a03b695c1bc21a0b48f7939b743e",
          "sha256": "ea7c90b186660a1cc17641f4a1c986d6f1a0ffcc8cf682effa94bbfdeacd9341",
          "sha1": "9a6a8248b6ea2d5df36868ff8881278bc1c2397c",
          "md5": "c4d0af565856c7b0288a9957b7069ea0"
        }
      ]
    }
  ]
}
