{
  "formatVersion": "1.1",
  "component": {
    "group": "transformer.plugin",
    "module": "transformerPlugin",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "transformerPlugin-0.0.2.jar",
          "url": "transformerPlugin-0.0.2.jar",
          "size": 23317,
          "sha512": "58226ed919c506209349783470915cd367e9d30710c992e4d6cedcae145eddea8b7614de6b5efc244498395b178fdba87c95a455cb69679699d5b7e9d5281ee1",
          "sha256": "97cb952316602051c202da83567bb2ee959e0a68ad48463388f737a8a83bbf3f",
          "sha1": "e05a2682b3c1037a1b0af3126d8f07d94dec98b3",
          "md5": "d6c2a609400cae25013c0ec6ac6ca36b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "transformerPlugin-0.0.2.jar",
          "url": "transformerPlugin-0.0.2.jar",
          "size": 23317,
          "sha512": "58226ed919c506209349783470915cd367e9d30710c992e4d6cedcae145eddea8b7614de6b5efc244498395b178fdba87c95a455cb69679699d5b7e9d5281ee1",
          "sha256": "97cb952316602051c202da83567bb2ee959e0a68ad48463388f737a8a83bbf3f",
          "sha1": "e05a2682b3c1037a1b0af3126d8f07d94dec98b3",
          "md5": "d6c2a609400cae25013c0ec6ac6ca36b"
        }
      ]
    }
  ]
}
