{
  "formatVersion": "1.1",
  "component": {
    "group": "transformer.plugin",
    "module": "transformerPlugin",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "transformerPlugin-0.0.2.jar",
          "url": "transformerPlugin-0.0.2.jar",
          "size": 19256,
          "sha512": "6a371edda1c92f90480acdbae72e8147fee4eb3245409237faec72168f8a9ffb1e88081853a6779f60d67f0125b97c8d797d005c759cb05b447b4465bb9c8865",
          "sha256": "0c084edc6cdce9c09d0cf41d78f02c94df01fb358b756405b58a45c420eeead4",
          "sha1": "0058391679220eee80fef84fad298129b1143599",
          "md5": "69a50a1e8b12a86689a72b0c2c881a77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "transformerPlugin-0.0.2.jar",
          "url": "transformerPlugin-0.0.2.jar",
          "size": 19256,
          "sha512": "6a371edda1c92f90480acdbae72e8147fee4eb3245409237faec72168f8a9ffb1e88081853a6779f60d67f0125b97c8d797d005c759cb05b447b4465bb9c8865",
          "sha256": "0c084edc6cdce9c09d0cf41d78f02c94df01fb358b756405b58a45c420eeead4",
          "sha1": "0058391679220eee80fef84fad298129b1143599",
          "md5": "69a50a1e8b12a86689a72b0c2c881a77"
        }
      ]
    }
  ]
}
