{
  "formatVersion": "1.1",
  "component": {
    "group": "transformer.plugin",
    "module": "transformerPlugin",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "transformerPlugin-0.0.2.jar",
          "url": "transformerPlugin-0.0.2.jar",
          "size": 22026,
          "sha512": "eb484f6b96217f9a9bf59e8f5e4fbb0bc872fde02be7689d6df2308038ff2a394a149b9fd2411727622bd6ce15945bb9af80154806caed11fd8a943851dc1d8f",
          "sha256": "9de9189ae51fa3e70b6b0e037dc82ea5ee1f1c1ea6e0fa20724fde01950d26d4",
          "sha1": "46adf41252723b65de30a3d3b6f78d449cef99af",
          "md5": "0a947c54aadb5eb130d7614932d6e77c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "transformerPlugin-0.0.2.jar",
          "url": "transformerPlugin-0.0.2.jar",
          "size": 22026,
          "sha512": "eb484f6b96217f9a9bf59e8f5e4fbb0bc872fde02be7689d6df2308038ff2a394a149b9fd2411727622bd6ce15945bb9af80154806caed11fd8a943851dc1d8f",
          "sha256": "9de9189ae51fa3e70b6b0e037dc82ea5ee1f1c1ea6e0fa20724fde01950d26d4",
          "sha1": "46adf41252723b65de30a3d3b6f78d449cef99af",
          "md5": "0a947c54aadb5eb130d7614932d6e77c"
        }
      ]
    }
  ]
}
